### ISSUE TITLE
Catalog not shown

### ISSUE THREAD

**Issue by L30MAX** [App-Fair/App#8]
Hi,
Unfortunately, only 21 apps are displayed for me. No matter what I set, only a few apps are shown. macOS 12.6 is installed.  

<img width="1193" alt="Bildschirmfoto 2022-10-16 um 16 16 45" src="https://user-images.githubusercontent.com/115937409/196041451-29e5a5b5-fda4-413a-a5c9-a565dbba9370.png">

**Comment by gushalgit** [comment]
Hi, 
I can confirm the experience of L30MAX.  Also non of the apps that have been installed via App Fair is showing up in the 'Installed' menu.
macOS 12.6 on a MacBook Pro M1

**Comment by marcprux** [comment]
The cataloging process got stuck. I've fixed it, so you should see the full 4,093 packages again.

**Comment by L30MAX** [comment]
It didn’t help… still the same problem

**Comment by marcprux** [comment]
Hmm .. the catalog should be the same as appears at https://appfair.net/fairapps-macos.html.

Can you post the version of the App Fair (from the "App Fair" -> "About" menu), and maybe a screenshot of what you are seeing?

**Comment by L30MAX** [comment]
AppFair version 0.8.130 (931)
I had the app some time ago, there were quite a few apps in the "Music" section. And at "Casks" was also the number of apps, over 3000, I think. This is all gone now in the current version.
<img width="1680" alt="Bildschirmfoto 2022-10-19 um 19 35 30" src="https://user-images.githubusercontent.com/115937409/196765217-0e2e991b-943f-4466-a552-a38db412940e.png">

**Comment by marcprux** [comment]
Can you try updating to 0.8.131 (either through the auto-update, or by manually downloading from https://appfair.app)? A few catalog quirks were addressed in that release. I'm running it now, and I see the full 4K apps in the Homebrew catalog.

If you still don't see the catalog, can you let me know what type of machine you are running on?

**Comment by L30MAX** [comment]
At least a partial success! Thanks a lot! Under Casks, around 4k apps are loaded when you scroll down further and further. But they don't show up in the categories on the left, the categories remain empty. On the screenshot as an example the category Music. This is how it looks in the other categories as well. 

<img width="1680" alt="Bildschirmfoto 2022-10-21 um 08 58 19" src="https://user-images.githubusercontent.com/115937409/197139310-c3f8af5f-7526-4eee-8680-0b23a04678b4.png">

<img width="1658" alt="Bildschirmfoto 2022-10-21 um 08 58 01" src="https://user-images.githubusercontent.com/115937409/197139346-1f5ea2d5-635e-4983-af7d-08b9d074499f.png">

**Comment by L30MAX** [comment]
I have updated the app. It runs on a Macbook Pro 15 2018.

**Comment by marcprux** [comment]
Categories should be showing up now. If not, please update this issue.
